sudo: required
services:
  - docker

before_install:
  - docker build -t markokostovski/docker-react -f Dockerfile.dev .

script:
  - docker run markokostovski/docker-react npm run test -- --coverage
